### ISSUE TITLE
Missing redirect to login form on successful registration.

### ISSUE THREAD

**Issue by mcgoode** [rcamp79/acme#1]
https://github.com/rcamp79/acme/blob/519616d0193b3d799976c306bfbe5a1e9d1112e0/src/Controller/AuthController.php#L51

When i registered as test@test.com it just was sent back to the registration page, and was unsure if it successfully registered. I registered 2 or 3 times before I tried to go to the login page to login. 

I would be curious if there are multiple emails with test@test.com registered now.

**Comment by mcgoode** [comment]
OH I see what is going on here... The issue was that test@test.com was already registered.

**Comment by mcgoode** [comment]
Fix by checking for an existing email address and warn the user. Maybe redirect to the login page?

**Comment by rcamp79** [comment]
I will look into this. It was showing a error message during registration
if an email was already registered. I'll check on why this is not working.

Thanks,

**Comment by rcamp79** [comment]
Issue resolved.
